#!/bin/bash
# install all scripts from /tools to /usr/sbin and /usr/lib
# so the user is able to use all these commands while running his/her Live Linux
#
# this script is automatically called by runme.sh
#
# Author: does it worth for such a short script ... hm... ok, Tomas M.
#

ROOT=$1

mkdir -p $ROOT/usr/sbin
mkdir -p $ROOT/usr/lib
ls -aA1b ./tools | egrep -v "^lib" | while read FILE; do cp ./tools/$FILE $ROOT/usr/sbin; done
ls -aA1b ./tools | egrep "^lib" | while read FILE; do cp ./tools/$FILE $ROOT/usr/lib; done

echo "Linux Live scripts were installed successfuly to $1/"
