#!/usr/bin/env ruby

rpms_dir = ""
if ARGV.length == 0
  rpms_dir = "."
else
  rpms_dir = ARGV[0].dup
end

if rpms_dir =~ /\/$/
  rpms_dir.chop!
end

rpms = Dir.glob("#{rpms_dir}/*.rpm").sort
prevr = rpms[0]
rpms.each do |r|
  name = r.split(/\//)[-1].split(/\-/)[0..-3].join("-")
  if prevr.split(/\//)[-1].split(/\-/)[0..-3].join("-") != name
    prevr = r
  else
    prevver = 0
    prevr.split(/\//)[-1].split(/\-/)[-2].split(/\./).each do |n|
      prevver *= 1000
      prevver += n.to_i
    end
    prevrel = 0
    prevr.split(/\//)[-1].split(/\-/)[-1].split(/\./)[0..-3].each do |n|
      prevrel *= 1000
      prevrel += n.to_i
    end
    ver = 0
    r.split(/\//)[-1].split(/\-/)[-2].split(/\./).each do |n|
      ver *= 1000
      ver += n.to_i
    end
    rel = 0
    r.split(/\//)[-1].split(/\-/)[-1].split(/\./)[0..-3].each do |n|
      rel *= 1000
      rel += n.to_i
    end
    if ver < prevver
      print "rm #{r}\n"
    elsif ver == prevver
      if rel < prevrel
	print "rm #{r}\n"
      elsif rel == prevrel
	next
      else
	print "rm #{prevr}\n"
      end
    else
      print "rm #{prevr}\n"
    end
  end
end
