#! /usr/bin/ruby -Ku
# -*- coding: utf-8 -*-
# depgraph-mini - SpecDB stub
# OmoiKondara not uses DepGraph methods except db. orz

load '../tools/updatespecdb'

class DepGraph
  attr_reader :db
  def initialize(verbose=false)
    @db = SpecDB.new(verbose)
    @db.freeze
  end
end
