#!/bin/bash

# test version
#
# by Hiromasa YOSHIMOTO <y@momonga-linux.org>

function error ()
{
	echo $@ > /dev/stderr
	exit 1
}

function usage ()
{
    cat<<EOF
usage:
$0  [opts]
    -a    list all status
    -e    list error status only
    -d    debug mode
    -h    display this help and exit
EOF
    exit 1
}

conf=report.config
log=report.log

[ -f $conf -a -r $conf ] || error "no report.config"
source $conf || error "failed to load $conf"
[ -n "$BRANCH" ] || error "bad config (no BRANCH)"

opts="-R -B $BRANCH"
while getopts "aehd" opt; do
    case $opt in
	h) 
	    usage
	    ;;
	a) 
	    unset log
	    ;;
	e) 
	    opts="$opts -s" 
	    ;;
	d)
	    opts="$opts -d"
	    ;;
    esac
done
shift $(($OPTIND -1))

FETCH=`dirname $0`/report/list-status.sh
[ -x $FETCH ] || error "no list-status.sh"

$FETCH $opts $log | awk -F, '{printf("%-60s%s\n",$1,$2)}'

exit $?
