#!/bin/sh

PATH=`dirname $0`:$PATH
eval `environment.rb`

if [ -z "$TOPDIR" ]; then
	exit 1
fi

# Run createrepo for top dir
function scan() {
	if [ -d $1 ]; then
		echo Scanning $1 1>&2
		opt="-v -d"
		if [ -f $1/repodata/repomd.xml ]; then
	 		opt="$opt --update"
		fi
		/usr/bin/createrepo $opt $1
	else
		echo $1 is not a directory. 1>&2
	fi
}

if [ $# = 0 ]; then
	set -- $TOPDIR*
fi

while [ $# -gt 0 ]; do
	case $1 in
	/*)
		scan $1;;
	*)
		scan `pwd`/$1;;
	esac
	shift
done
