#!/usr/bin/ruby -Ku
# by Hiromasa YOSHIMOTO <y@momonga-linux.org>

require 'optparse'

OPTS = {}
Version = "0.0.1"

$:.unshift(File.dirname($0))
require 'lib/config.rb'
require 'lib/pkgdb.rb'

opt = OptionParser.new
opt.on('-q', '--quite', 'suppress verbose msg.') {|v| OPTS[:verbose]=-1 }
opt.on('-v', '--verbose', 'verbose msg.') {|v| OPTS[:verbose]+=1 }
opt.parse!(ARGV)

OPTS[:readonly] = true

d = PkgDB.new
d.open(OPTS[:pkgdb_filename], OPTS)
db = d.db

curr = ARGV 
curr.map!{|v| v.chomp("/") }

curr.each do |cap|    
  sql = "SELECT pkgfile FROM capability_tbl INNER JOIN pkg_tbl ON owner=id WHERE capability GLOB '#{cap}'"
  db.execute(sql) do |pkgfile,|
    print "#{pkgfile}\n"
  end
end

# Local Variables:
# mode: ruby
# indent-tabs-mode: nil
# End:
