#!/usr/bin/ruby -Ku
# by Hiromasa YOSHIMOTO <y@momonga-linux.org>

require 'optparse'

OPTS = {}
Version = "0.0.1"

$:.unshift(File.dirname($0))
require 'lib/config.rb'
require 'lib/pkgdb.rb'

opt = OptionParser.new
MoConfig.parse(ARGV,opt)

OPTS[:readonly] = true

d = PkgDB.new
d.open(OPTS[:pkgdb_filename], OPTS)
db = d.db

curr = ARGV 
curr.map!{|v| v.chomp("/") }

curr.each do |pkgfile| 
  sql = "SELECT capability FROM capability_tbl INNER JOIN pkg_tbl ON id==owner WHERE pkgfile GLOB '#{pkgfile}'"
  db.execute(sql) do |cap,|
    print "#{cap}\n"
  end
end

# Local Variables:
# mode: ruby
# indent-tabs-mode: nil
# End:
