#!/usr/bin/ruby -Ku
# by Hiromasa YOSHIMOTO <y@momonga-linux.org>

require 'optparse'
$:.unshift(File.dirname($0))

OPTS = {}
Version = "0.0.1"
require 'lib/config.rb'
require 'lib/prepare.rb'

OPTS[:verbose] = 10
OPTS[:debug]   = true

opt = OptionParser.new
MoConfig.parse(ARGV,opt)

requested = ARGV 
requested.map!{|v| v.chomp("/") }

requested.each {|specdir|
  job = Job.new("#{specdir}/#{specdir}.spec", nil, OPTS)

  next if ! job.valid

  job.prepare_sources
}

# Local Variables:
# mode: ruby
# indent-tabs-mode: nil
# End:
