#!/usr/bin/ruby
# -*- coding: utf-8 -*-
# by Hiromasa YOSHIMOTO <y@momonga-linux.org>

require 'optparse'

OPTS = {}
Version = "0.0.1"

$:.unshift(File.dirname($0))
require 'lib/config.rb'
require 'lib/pkgdb.rb'

ignorepath = []

opt = OptionParser.new
opt.on('--ignore=PATH', 'ignore PATH') {|v| ignorepath.push(v)}
MoConfig.parse(ARGV,opt)

#OPTS[:readonly] = true

d = PkgDB.new
d.open(OPTS[:pkgdb_filename], OPTS)
db = d.db

require 'set'
delQ = Set.new
pkgs = Set.new
sql = 'SELECT pkgname,arch,id,lastupdate FROM pkg_tbl'
db.execute(sql) do |pkgname,arch,|
  name="#{pkgname}.#{arch}"
  if pkgs.include?(name) then
    delQ.add([pkgname,arch])
  else
    pkgs.add(name)
  end
end

delQ.each do |name,arch|
  db.execute('DELETE FROM pkg_tbl WHERE pkgname LIKE ? AND arch LIKE ?',
             [name, arch])
end

exit

# Local Variables:
# mode: ruby
# indent-tabs-mode: nil
# End:
