#!/usr/bin/ruby -Ku
#
# by Hiromasa YOSHIMOTO <y@momonga-linux.org>

require 'optparse'
require 'set'

OPTS = {}
Version = "0.0.1"

$:.unshift(File.dirname($0))
require 'lib/config.rb'
require 'lib/specdb.rb'

OPTS[:recursion]=1
opt = OptionParser.new
opt.on('-r N', '--recursion=N', 'max depth') {|v| OPTS[:recursion] = Integer(v) }
opt.on('-f', '--force_update') {|v| OPTS[:force_update] = v }
opt.on('-q', '--quite', 'suppress verbose msg.') {|v| OPTS[:verbose]=-1 }
opt.on('-v', '--verbose', 'verbose msg.') {|v| OPTS[:verbose]+=1 }
opt.parse!(ARGV)

OPTS[:readonly] = true

d = SpecDB.new
d.open(OPTS[:specdb_filename], OPTS)
db = d.db

pkgs = Set.new
curr = ARGV
curr.map!{|v| v.chomp("/") }

loop=0

while loop < OPTS[:recursion] 
  print "\n" if (loop>0)

  STDERR.puts "loop #{loop}" if (OPTS[:verbose]>1)

  loop += 1

  found = Set.new
  candidates = Set.new

  curr.each do |name|
    sql = "SELECT id FROM specfile_tbl WHERE name GLOB '#{name}'"
    db.execute(sql) do |id,|
      candidates.add(id)
    end
#    sql = "SELECT owner FROM capa_view WHERE capability GLOB '#{name}'"
#    db.execute(sql) do |owner,|
#      candidates.add(owner)
#    end
  end

  candidates.each do |id|
    sql = "SELECT capability FROM buildreq_tbl WHERE owner == '#{id}'"
    db.execute(sql) do |cap,|
      sql = "SELECT name FROM capa_view INNER JOIN specfile_tbl ON owner=id WHERE capability == '#{cap}' GROUP BY name"
      db.execute(sql) do |pkg,|
        if !pkgs.include?(pkg) then
          found.add(pkg)
        end
      end
    end
  end
  
  if found.empty? then
    break
  end


  found.each do |name|
    print "#{name}\n"
  end

  pkgs.merge(found)
  curr = found
end # end of while loop

db.close()

# Local Variables:
# mode: ruby
# indent-tabs-mode: nil
# End:
