#!/usr/bin/ruby -Ku
#
# by Hiromasa YOSHIMOTO <y@momonga-linux.org>

require 'optparse'
require 'set'

OPTS = {}
Version = "0.0.1"

$:.unshift(File.dirname($0))
require 'lib/config.rb'
require 'lib/specdb.rb'

OPTS[:recursion]=1
opt = OptionParser.new
MoConfig.parse(ARGV,opt)

OPTS[:readonly] = true

d = SpecDB.new
d.open(OPTS[:specdb_filename], OPTS)
db = d.db

provs = Set.new
curr = ARGV
curr.map!{|v| v.chomp("/") }

candidates = Set.new

curr.each do |name|   
  sql = "SELECT owner FROM capa_view WHERE capability GLOB '#{name}' "
  db.execute(sql) do |owner,|
    candidates.add(owner)
  end
end

candidates.each do |id|
  sql = "SELECT capability FROM capa_view WHERE owner=='#{id}' GROUP BY capability"
  db.execute(sql) do |cap,|
    print "#{cap}\n"
  end
end

db.close()

# Local Variables:
# mode: ruby
# indent-tabs-mode: nil
# End:
