#!/usr/bin/ruby -Ku
#
# by Hiromasa YOSHIMOTO <y@momonga-linux.org>

require 'optparse'
require 'set'

Version = "0.0.1"
OPTS = {}

$:.unshift(File.dirname($0))
require 'lib/config.rb'
require 'lib/specdb.rb'

OPTS[:recursion]=1
opt = OptionParser.new
opt.on('-f', '--force_update') {|v| OPTS[:force_update] = v }
opt.on('-q', '--quite', 'suppress verbose msg.') {|v| OPTS[:verbose]=-1 }
opt.on('-v', '--verbose', 'verbose msg.') {|v| OPTS[:verbose]+=1 }
opt.parse!(ARGV)

OPTS[:readonly] = true

d = SpecDB.new
d.open(OPTS[:specdb_filename], OPTS)
db = d.db

curr = ARGV
curr.map!{|v| v.chomp("/") }


candidates = Set.new

curr.each do |name|   
  sql = "SELECT capability FROM capa_view WHERE capability GLOB '#{name}' "
  db.execute(sql) do |cand,|
    candidates.add(cand)
  end
end

candidates.each do |name|
  sql = "SELECT name FROM capa_view INNER JOIN specfile_tbl ON owner==id WHERE capability == '#{name}' GROUP BY name "
  db.execute(sql) do |pkg,|
    print "#{pkg}\n"
  end
end

db.close()


# Local Variables:
# mode: ruby
# indent-tabs-mode: nil
# End:
