#!/usr/bin/ruby -Ku
# by Hiromasa YOSHIMOTO <y@momonga-linux.org>


require 'optparse'

OPTS = {}
Version = "0.0.1"

$:.unshift(File.dirname($0))
require 'lib/config.rb'
require 'lib/pkgdb.rb'

opt = OptionParser.new
MoConfig.parse(ARGV,opt)

OPTS[:readonly] = true

d = PkgDB.new
d.open(OPTS[:pkgdb_filename], OPTS)
db = d.db

curr = ARGV 
curr.map!{|v| v.chomp("/") }

curr.each do |cap|    
  sql = "SELECT path,pkgfile FROM file_tbl INNER JOIN pkg_tbl ON owner=id WHERE path GLOB '*#{cap}*'"
  db.execute(sql) do |path,pkgfile,|
    print "#{path}\n"
    print "#{pkgfile}\n"
  end
  sql = "SELECT capability,pkgfile FROM capability_tbl INNER JOIN pkg_tbl ON owner=id WHERE capability GLOB '#{cap}'"
  db.execute(sql) do |cap,pkgfile,|
    print "#{cap}\n"
    print "#{pkgfile}\n"
  end
end

# Local Variables:
# mode: ruby
# indent-tabs-mode: nil
# End:
