#!/usr/bin/ruby
#
# by Hiromasa YOSHIMOTO <y@momonga-linux.org>

require 'optparse'
require 'sqlite3'
require 'set'

Version = "0.0.1"
OPTS = {}

$:.unshift(File.dirname($0))
require 'lib/config.rb'

OPTS[:recursion]=1
opt = OptionParser.new
opt.on('-f', '--force_update') {|v| OPTS[:force_update] = v }
opt.on('-q', '--quite', 'suppress verbose msg.') {|v| OPTS[:verbose]=-1 }
opt.on('-v', '--verbose', 'verbose msg.') {|v| OPTS[:verbose]+=1 }
opt.parse!(ARGV)

db = SQLite3::Database.new(OPTS[:specdb_filename])

p "not implemented yet"

# Local Variables:
# mode: ruby
# indent-tabs-mode: nil
# End:
