#!/usr/bin/ruby -Ku
#
# by Hiromasa YOSHIMOTO <y@momonga-linux.org>

Version = "0.0.1"
OPTS = {}

require 'optparse'
require 'set'

$:.unshift(File.dirname($0))
require 'lib/config.rb'
require 'lib/specdb.rb'

opt = OptionParser.new
opt.on('-f', '--force_update') {|v| OPTS[:force_update] = v }
opt.on('-q', '--quite', 'suppress verbose msg.') {|v| OPTS[:verbose]=-1 }
opt.on('-v', '--verbose', 'verbose msg.') {|v| OPTS[:verbose]+=1 }
opt.parse!(ARGV)


d = SpecDB.new
d.open(OPTS[:specdb_filename], OPTS)

# update or insert entries to databse
if ARGV.size == 0 then
  removeQ = Set.new
  addQ = Set.new
  d.db.execute("select name from specfile_tbl") do |name,|
    removeQ.add(name)
  end
  
  Dir.open('.').each do |dirname,|
    name = File.basename(dirname)    
    if File.exist?("#{name}/#{name}.spec") then
      addQ.add(name)
      removeQ.delete(name)
    end
  end

  d.update_list(addQ, OPTS)
  d.delete_list(removeQ, OPTS)
else
  d.update_list(ARGV, OPTS)
end


d.check(OPTS)

d.close

# Local Variables:
# mode: ruby
# indent-tabs-mode: nil
# End:
