#!/usr/bin/ruby -rubygems
#
# by Hiromasa YOSHIMOTO <y@momonga-linux.org>

require 'optparse'
require 'sqlite3'
require 'set'

OPTS = {}
Version = "0.0.1"

$:.unshift(File.dirname($0))
require 'lib/config.rb'

OPTS[:recursion]=1
opt = OptionParser.new
opt.on('-f', '--force_update') {|v| OPTS[:force_update] = v }
opt.on('-q', '--quite', 'suppress verbose msg.') {|v| OPTS[:verbose]=-1 }
opt.on('-v', '--verbose', 'verbose msg.') {|v| OPTS[:verbose]+=1 }
opt.parse!(ARGV)


db = SQLite3::Database.new(OPTS[:specdb_filename])

provs = Set.new
curr = ARGV
curr.map!{|v| v.chomp("/") }

candidates = Set.new

curr.each do |name|   
  sql = "SELECT owner FROM capa_view WHERE capability GLOB '#{name}' "
  db.execute(sql) do |owner,*|
    candidates.add(owner)
  end
end

candidates.each do |id|
  sql = "SELECT capability FROM capa_view WHERE owner=='#{id}' GROUP BY capability"
  db.execute(sql) do |cap,*|
    print "#{cap}\n"
  end
end

db.close()

# Local Variables:
# mode: ruby
# indent-tabs-mode: nil
# End:
