#!/usr/bin/ruby -Ku
# -*- coding: utf-8 -*-
# by Hiromasa YOSHIMOTO <y@momonga-linux.org>

require 'optparse'
require 'set'

OPTS = {}
Version = "0.0.1"

$:.unshift(File.dirname($0))
require 'lib/config.rb'
require 'lib/install.rb'
require 'lib/pkgdb.rb'
require 'lib/upgrade.rb'

OPTS[:strict]=false
OPTS[:verbose]+=1
OPTS[:max_retry]=64
opt = OptionParser.new
opt.on('-S', '--strict', 'strict mode') {|v| OPTS[:strict]=true }
opt.on(      '--permissive', 'permissive mode (default)') {|v| OPTS[:strict]=false }
MoConfig.parse(ARGV,opt)

OPTS[:readonly] = true

d = PkgDB.new
d.open(OPTS[:pkgdb_filename], OPTS)

# Retrieves installed packages and its buildtimes
installed = []
`LANG=C \\rpm -qa --qf '%{NAME},%{VERSION},%{RELEASE},%{BUILDTIME},%{ARCH}\n'`.each_line do |line|
  column = line.chomp.split(',')
  v  = column[1]
  v += "-#{column[2]}" if column[2]!=""
  installed.push([column[0],v,column[3].to_i,column[4]])
end

if true == OPTS[:strict] then
  upgrade_strict(installed, d, OPTS)
else
  upgrade_permissive(installed, d, OPTS)
end

exit(0)

# Local Variables:
# mode: ruby
# indent-tabs-mode: nil
# End:
