#!/bin/bash
# convert directory tree into .MO compressed file
# which can be used as a LiveCD module
#
# Author: Tomas M. <http://www.linux-live.org>
#

if [ -a ./liblinuxlive ]; then
   . ./liblinuxlive
else
   . /usr/lib/liblinuxlive || exit 1
fi

if [ ! -d "$1" -o "$2" = "" ]; then
   echo
   echo "Convert directory tree into .MO compressed module"
   echo "usage: $0 source_directory output_file.mo"
   exit 1
fi

create_module "$1" "$2"
if [ $? != 0 ]; then echo "error building compressed image"; exit 1; fi
