#!/bin/bash
# This is a config file for runme.sh script.
# You shouldn't need to change anything.

# compressed directories (img) will be stored here
# (the whole folder will be erased now!)
CDDATA=/tmp/live_data_$$

# name of initrd image
INITRDIMG=initrd

# the size of RAMdisk (in KBytes)
# if you change this, then you will need to change the size
# also in the following files: ./cd-root/isolinux.cfg, ./cd-root/boot/DOS/config
RAM0SIZE=8192
#RAM0SIZE=4444

# kernel version. Change it to "2.6.10" for example, if you are building
# LiveCD with a different kernel than the one you are actually running
KERNEL="`uname -r`"

# change this variable if you installed your distro to some directory.
# for example ROOT=/tmp/newdir. You may leave it empty, then it defaults to /
#ROOT=/live-env

